### ISSUE TITLE
How access the directory path defined in config.yml in a controller

### ISSUE THREAD

**Issue by jfsenechal** [1up-lab/OneupUploaderBundle#108]
Hi, 

How can I get the path in my controller for example :

``` php
$directory = '/var/www/sepul/web/uploads/gallery/'; //bad
$directory = $this->container->get('oneup???')->get('gallery');
$finder->files()->in($directory);
... 
```

My config :

``` yml
oneup_uploader:    
    mappings:
        gallery:
            frontend: blueimp # or any uploader you use in the frontend
            use_orphanage: false                 
            storage:
                type: gaufrette
                filesystem: gaufrette.gallery_filesystem  

knp_gaufrette:
    stream_wrapper: ~

    adapters:
        gallery:
            local:
                directory: %kernel.root_dir%/../web/uploads/gallery
```

Thanks
