### ISSUE TITLE
Orphanage + Amazon S3

### ISSUE THREAD

**Issue by umpirsky** [1up-lab/OneupUploaderBundle#122]
Here is my config:

``` yml
knp_gaufrette:
    adapters:
        amazon_s3:
            aws_s3:
                service_id: 'my.s3'
                bucket_name: %amazon_s3.bucket_name%
                options:
                    directory: 'media'
    filesystems:
        amazon_s3:
            adapter: amazon_s3

oneup_uploader:
    mappings:
        gallery:
            use_orphanage: true
            frontend: dropzone
            namer: my.namer.uniqid
            storage:
                type: gaufrette
                filesystem: gaufrette.amazon_s3_filesystem
    orphanage:
        directory: %sylius.media.tmp_path%
```

When I configure uploader to work with local filesystem, it works fine, but with s3, I get:

```
exception 'Gaufrette\Exception\FileNotFound' with message 'The file "/8b/2b/0ff49efe31223d82ef57d4286a2b.jpg" was not found.' in vendor/knplabs/gaufrette/src/Gaufrette/Filesystem.php:292
Stack trace:
#0 vendor/knplabs/gaufrette/src/Gaufrette/Filesystem.php(87): Gaufrette\Filesystem->assertHasFile('/8b/2b/0ff49efe...')
#1 vendor/oneup/uploader-bundle/Oneup/UploaderBundle/Uploader/Storage/GaufretteStorage.php(52): Gaufrette\Filesystem->get('/8b/2b/0ff49efe...')
#2 vendor/oneup/uploader-bundle/Oneup/UploaderBundle/Uploader/Storage/FilesystemOrphanageStorage.php(51): Oneup\UploaderBundle\Uploader\Storage\GaufretteStorage->upload(Object(Oneup\UploaderBundle\Uploader\File\FilesystemFile), '/8b/2b/0ff49efe...')
#3 src/Umpirsky/Bundle/CoreBundle/EventListener/ImageUploadListener.php(25): Oneup\UploaderBundle\Uploader\Storage\FilesystemOrphanageStorage->uploadFiles()
#4 [internal function]: Umpirsky\Bundle\CoreBundle\EventListener\ImageUploadListener->onUpload(Object(Sylius\Bundle\ResourceBundle\Event\ResourceEvent))
#5 vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Sylius\Bundle\ResourceBundle\Event\ResourceEvent))
#6 vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'sylius.product....', Object(Sylius\Bundle\ResourceBundle\Event\ResourceEvent))
#7 vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php(167): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('sylius.product....', Object(Sylius\Bundle\ResourceBundle\Event\ResourceEvent))
#8 vendor/sylius/sylius/src/Sylius/Bundle/ResourceBundle/Controller/DomainManager.php(174): Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('sylius.product....', Object(Sylius\Bundle\ResourceBundle\Event\ResourceEvent))
#9 src/Umpirsky/Bundle/CoreBundle/Controller/ProductController.php(62): Sylius\Bundle\ResourceBundle\Controller\DomainManager->dispatchEvent('pre_upload', Object(Sylius\Bundle\ResourceBundle\Event\ResourceEvent))
#10 [internal function]: Umpirsky\Bundle\CoreBundle\Controller\ProductController->createAction(Object(Symfony\Component\HttpFoundation\Request))
#11 app/bootstrap.php.cache(2863): call_user_func_array(Array, Array)
#12 app/bootstrap.php.cache(2837): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#13 app/bootstrap.php.cache(2966): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 app/bootstrap.php.cache(2246): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 web/app_dev.php(42): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#16 {main}
```

This is debug dump, since this exception is ignored in https://github.com/1up-lab/OneupUploaderBundle/blob/master/Uploader/Storage/FilesystemOrphanageStorage.php#L55-L57. Not sure why?

My guess is that `Oneup\UploaderBundle\Uploader\Storage\GaufretteStorage` in line 52 tries to get file from s3 `return new GaufretteFile($this->filesystem->get($path), $this->filesystem, $this->streamWrapperPrefix);` instead from local file system in order to upload it to s3. And file is not there yet.
