### ISSUE TITLE
What are the different frontends that can be set with OneupUploaderBundle?

### ISSUE THREAD

**Issue by mappedinn** [1up-lab/OneupUploaderBundle#140]
What are the different frontends that can be set with OneupUploaderBundle in the config.yml file?
I googled this and I found some frontend like: `mooupload`, `blueimp`. 

What is the full list?

```
# app/config/config.yml
oneup_uploader:
    mappings:
        gallery:
            frontend: blueimp # or any uploader you use in the frontend
```

Is it possible to use [VichUploaderBunde](https://github.com/dustin10/VichUploaderBundle) as frontend in OneupUploaderBundle?
