### ISSUE TITLE
Gaufrette orphanage

### ISSUE THREAD

**Issue by Looted** [1up-lab/OneupUploaderBundle#159]
Hello!
I have a question regarding orphanage with the gaufrette filesystem. I need to use orphanage along with Amazon S3. I need to implement removing items from orphanage however, so files can be dynamically removed from dropzone (so that if someone uploads two files, removes one and submits the form, only one gets moved from the orphanage). Right now the config is as follows:

```
oneup_uploader:
    mappings:
        job_pdf:
            frontend: dropzone
            storage:
                type: gaufrette
                filesystem: gaufrette.test_filesystem
            use_orphanage: true
    orphanage:
        maxage: 86400
    directory: orphanage
```

The filesystem points to web/uploads for now (it will be switched to Amazon S3 on production server). The orphanage saves files outside the filesystem however - not relative to the filesystem root. It should be web/uploads/orphanage, but saves to web/orphanage. Please advise. 

With regards
