### ISSUE TITLE
uri prefix

### ISSUE THREAD

**Issue by olegkhuss** [1up-lab/OneupUploaderBundle#172]
Hi,
I don't see any helpers to point a file name to a web url? I could do a pull if needed
Thanks

Something like 
```
oneup_uploader:
    mappings:
        gallery:
            ....
            storage:
                directory: %kernel.root_dir%/../web/uploads/gallery
                uri_prefix: /web/uploads/gallery # extra option <--
        gallery2:
            ....
```

```
{{ oneup_uploader_uri_prefix('myfile.jpg', 'gallery') }}
# output  /web/uploads/gallery/myfile.jpg
```
