### ISSUE TITLE
File "" cannot be opened

### ISSUE THREAD

**Issue by vgross** [1up-lab/OneupUploaderBundle#195]
I've setup this uploader using the Plugin jQuery File Upload and gaufrette storage...

I could manage to make everything working to upload an image but when I upload an mp3, the response from the AJAX call is:

{"error":{"code":500,"message":"Internal Server Error","exception":[{"message":"File \"\" cannot be opened","class":"RuntimeException","trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/Users\/vince\/Sites\/localcrea.com\/vendor\/knplabs\/gaufrette\/src\/Gaufrette\/Stream\/Local.php","line":45,"args":[]},{"namespace":"Gaufrette\Stream","short_class":"Local","class":"Gaufrette\Stream\Local","type":"->","function":"open","file":"\/Users\/vince\/Sites\/localcrea.com\/vendor\/oneup\/uploader-bundle\/Oneup\/UploaderBundle\/Uploader\/Gaufrette\/StreamManager.php","line":40,"args":[["object","Gaufrette\StreamMode"]]},

...

[["object","Symfony\Component\HttpFoundation\Request"]]}]}]}}

The entire folder got the correct permission and I can't figured out why it's working with images and not with mp3...

Is anyone can give me a hand?

**Comment by vgross** [comment]
Maybe with some piece of code it will be better...

Hope someone can help me on that as I spent maybe 4 days on that bug so far...

Here my config.yml:

```yml
oneup_uploader:
    mappings:
        image_song:
            frontend: blueimp
            storage:
                type: gaufrette
                filesystem: gaufrette.image_song_filesystem
            error_handler: oneup_uploader.error_handler.blueimp
        song_creatoke:
            frontend: blueimp
            storage:
                type: gaufrette
                filesystem: gaufrette.song_creatoke_filesystem
            error_handler: oneup_uploader.error_handler.blueimp
...

knp_gaufrette:
    adapters:
        image_song:
            local:
                directory: %kernel.root_dir%/../web/uploads/creatoke/images/song
                create: true
        song_creatoke:
            local:
                directory: %kernel.root_dir%/../web/uploads/creatoke/songs/creatoke
                create: true
...

    filesystems:
        image_song:
            adapter:    image_song
        song_creatoke:
            adapter:    song_creatoke
```

My front end:

```html
<div class="row-fluid top_padded row-uploader">
                    <div class="span3"> 
                        Télécharger une image :
                    </div>
                    <div class="span2"> 
                        <span class="btn btn-success fileinput-button">
                            <i class="icon-plus icon-white"></i>
                            <span>Fichier...</span>
                            <input id="upload_image" class="creatoke-uploader" type="file" name="files[]" data-url="{{ oneup_uploader_endpoint('image_song') }}" />
                        </span>
                    </div>
                    <div class="span5"> 
                        <div id="progress_image" class="progress progress-success progress-striped">
                            <div class="bar"></div>
                        </div>
                    </div>
                    <div class="span2"> 
                        <div id="files_image" class="files"></div> 
                    </div>
                </div>
<div class="row-fluid top_padded row-uploader">
                    <div class="span3"> 
                        Télécharger mp3 Creatoke complet :
                    </div>
                    <div class="span2"> 
                        <span class="btn btn-success fileinput-button">
                            <i class="icon-plus icon-white"></i>
                            <span>Fichier...</span>
                            <input id="upload_song_tosell" class="creatoke-uploader" type="file" name="files[]" data-url="{{ oneup_uploader_endpoint('song_creatoke') }}" />
                        </span>
                    </div>
                    <div class="span5"> 
                        <div id="progress_song_tosell" class="progress progress-success progress-striped">
                            <div class="bar"></div>
                        </div>
                    </div>
                    <div class="span2"> 
                        <div id="files_song_tosell" class="files"></div> 
                    </div>
                </div>
```

```javascript
            $('.creatoke-uploader').fileupload({
                url: $(this).data('url'),
                dataType: 'json',
                formData: {
                    entity_id:   '{{ entity.id }}'
                },
                done: function (e, data) {
                    console.log(data);
                    if (data.result.fichier != undefined)
                    {
                        var file_image = $(this).parent().parent().next("div").next("div").find(".files");
                        file_image.empty();
                        $('<p/>').text('Fichier ok!').appendTo(file_image);
                        if($(this).attr("id") == "upload_image") {
                            $("#img_preview").attr('src', data.result.fichier);
                        }
                    }
                    else
                    {
                        var bar = $(this).parent().parent().next("div").find(".bar");
                        alert(data.result.files[0].error);
                        $(bar).css('width','0%');
                    }
                },
                progressall: function (e, data) {
                    var bar = $(this).parent().parent().next("div").find(".bar");
                    var progress = parseInt(data.loaded / data.total * 100, 10);
                    $(bar).css('width',progress + '%');
                }
            }).prop('disabled', !$.support.fileInput)
                    .parent().addClass($.support.fileInput ? undefined : 'disabled');
```

In that exemple in particular, on both uploader, I can only upload images, if I select a mp3 file, I got the error "File \"\" cannot be opened" from "/vendor\/knplabs\/gaufrette\/src\/Gaufrette\/Stream\/Local.php". 

Please let me know if you need more? @bytehead ? @sheeep ? any thought?
