### ISSUE TITLE
Add random namer for security cases

### ISSUE THREAD

**Issue by JHGitty** [1up-lab/OneupUploaderBundle#199]
There should be a namer which provides **unique** and **random** file names.
The ``UniqueidNamer`` is not cryptographically secure random.

The default upload directory is in the ``web`` directory. This could result in security issues if you like to prevent crawling of all your uploaded files.

The ``uniqid()`` php function is not random:

> This function does not create random nor unpredictable strings. This function must not be used for security purposes. Use a cryptographically secure random function/generator and cryptographically secure hash functions to create unpredictable secure IDs.

Source: http://php.net/manual/en/function.uniqid.php

**Comment by lsv** [comment]
Quite easy to make your own namer.

```php
class MyNamer  implements NamerInterface {

   public function name(FileInterface $file)
   {
        // Same method as Symfony uri safe token generator uses
        // And in Symfony >= 2.7, random_bytes function has polyfills for lower PHP versions
        $bytes = random_bytes(256 / 8);
        return rtrim(strtr(base64_encode($bytes), '+/', '-_'), '=') . '.' . $file->getExtension();
   }

}
```

```yml
# service.yml
services:
    my_unique_namer:
        class: MyNamer
```

```yml
# config.yml
oneup_uploader:
    mappings:
        gallery:
            namer: my_unique_namer
```
