### ISSUE TITLE
How to get route in JavaScript?

### ISSUE THREAD

**Issue by nask0** [1up-lab/OneupUploaderBundle#204]
Hi, i use Fos js routing, but it seems that upload routes are not exposed there. 
Is there a known way to get uploader/upload route in JavaScript?

**Comment by nask0** [comment]
Silly workaround:
<dump routes first and find your>
```
uploader_route_test:
   pattern: /_uploader/<mapping_name>/upload
   options:
      expose: true
```
