### ISSUE TITLE
File path in twig

### ISSUE THREAD

**Issue by deviprsd21** [1up-lab/OneupUploaderBundle#234]
How will I get the file path in twig? I previously used viichuploader, and it had a twig function to generate the file url! I don't want to save the file path in the database, to save database size.

**Comment by bytehead** [comment]
As easy as it can get! :)
You don't have to store the whole path.

Just configure your upload directory: 
```yml
oneup_uploader:
    mappings:
        gallery:
            storage:
                filesystem: %kernel.root_dir%/../web/uploads/gallery
```

and in twig you can use it like this: 

```twig
<img src="/uploads/gallery{{ image.path }}" />
```
