### ISSUE TITLE
Unnamed directory when uploading to Amazon S3

### ISSUE THREAD

**Issue by diegotham** [1up-lab/OneupUploaderBundle#241]
When I upload images to Amazon S3 it creates a new folder inside the folder I specify:

```
// Oneup
oneup_uploader:
    mappings:
        gallery:
            frontend: dropzone
            use_orphanage: true
            storage:
                type: gaufrette
                filesystem: gaufrette.gallery_filesystem
                sync_buffer_size: 1M
    orphanage:
        maxage: 86400
        directory: %kernel.cache_dir%/uploader/orphanage

// Gaufrette
knp_gaufrette:
    adapters:
        gallery:
            aws_s3:
                service_id: "ms.amazon.s3" 
                bucket_name: "%amazon_s3_bucket_name%"
                options:
                    directory: listings
                    create: false

    filesystems:
        gallery:
            adapter: gallery

// Services
    ms.amazon.s3Credentials:
        class: Aws\Credentials\Credentials
        arguments: ["%amazon_aws_key%", "%amazon_aws_secret_key%"]

    ms.amazon.s3:
        class: Aws\S3\S3Client
        arguments:
            - version: %amazon_s3_version%
              region: %amazon_s3_region%
              credentials: "@ms.amazon.s3Credentials"
```

In this case the directory is "listings". It uploads the archives correctly, but inside "listings//" (it creates an unnamed folder). Does anyone knows what could be wrong? I use LiipImagineBundle that stores cache of thumbnails in Amazon S3 and it stores it in the right directory (not creating an unnamed directory).
