### ISSUE TITLE
How to modify storage path with dynamic data ?

### ISSUE THREAD

**Issue by eved42** [1up-lab/OneupUploaderBundle#250]
Hi,

I have an entity Product and I want to associate it files (images, pdf, word...).

Here is my config : 
```
oneup_uploader:
   mappings:
      product_image:
         frontend: blueimp
         namer: app.product_image_namer
         storage:
            directory: %kernel.root_dir%/../web/images/products

      product_doc:
         frontend: blueimp
         storage:
            directory: %kernel.root_dir%/../web/docs/products
```
Is it possible to modify storage path in order to include product id ? Something like this : 
```
storage:
    directory: %kernel.root_dir%/../web/docs/products/%product_id%
```
For images, I use a specific file namer because I name them like this : productid_indexnumber.jpg
The namer checks if a file already exists and increments the index number.

But for documents, I want to keep the original file name and save the document in a sub directory.
