### ISSUE TITLE
I don't have response with OneupUploaderBundle

### ISSUE THREAD

**Issue by GaylordP** [1up-lab/OneupUploaderBundle#257]
Hello and thank you for your Bundle,

With OneupuploaderBundle (and blueimp) for Symfony, I don't have response in Javascript :

**PHP Listener :**

```
namespace LogicielBundle\Listener;

use Oneup\UploaderBundle\Event\PostPersistEvent;

class UploadListener
{

    public function onUpload(PostPersistEvent $event)
    {
        $response = $event->getResponse();
        $response['coucou'] = 'hello';
    }

}
```

**Service :** 

```
logiciel.upload_listener:
    class: LogicielBundle\Listener\UploadListener
    tags:
        - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }
```

**Javascript :** 

```
$('.file_upload:last').fileupload({
    dataType: 'json',
    url: '/app_dev.php/_uploader/gallery/upload',
    disableImageResize: /Android(?!.*Chrome)|Opera/
        .test(window.navigator && navigator.userAgent),
    imageMaxWidth: 1200,
    imageMaxHeight: 1200,
    previewMaxWidth : 350,
    previewMaxHeight : 350,
    imageCrop: false,
    autoUpload: true,
    done: function (e, data) {
        console.log(data.result.coucou); // undefined
    }
});
```

Can you help me please ? And sorry for my bad english, I'm french :/
