### ISSUE TITLE
Multiple custom uploaders

### ISSUE THREAD

**Issue by pablocaviglia** [1up-lab/OneupUploaderBundle#274]
Hi, i'd like to know if it's something that is already implemented but i'm using wrongly, or if it's not supported at all.

I want to define two different custom mappings, with two different managers and different validation rules.

```
oneup_uploader:
    mappings:
        profile_picture:
            frontend: custom
            custom_frontend:
                class: ApiBundle\Controller\Uploader\ProfilePictureFileUploader
                name: profile_picture
            storage:
                directory: ""
            max_size: 1048576 # 1 mb
            allowed_mimetypes:
                - 'image/jpeg'
                - 'image/png'

        adventure_picture:
            frontend: custom
            custom_frontend:
                class: ApiBundle\Controller\Uploader\AdventureImageFileUploader
                name: adventure_picture
            storage:
                directory: ""
            max_size: 2097146 # 2 mb
            allowed_mimetypes:
                - 'image/png'



```
