### ISSUE TITLE
Symfony3 & Custom Namer - ServiceNotFoundException

### ISSUE THREAD

**Issue by milan74sa** [1up-lab/OneupUploaderBundle#281]
```yml
config.yml
oneup_uploader:
    mappings:
        ad_attachments:
            namer: app.oneup_uploader_namer
            frontend: plupload
            storage:
                directory: "warehouse/ad_attachments"
```
```yml
services.yml
    app.oneup_uploader_namer:
        class: AppBundle\EventListener\OneupUploaderNamer
        arguments: ["@request_stack"]
```
**when I tried to use, I everytime get:**
```php

request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException:
"You have requested a non-existent service "app.oneup_uploader_namer"." at /vagrant/application/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/
Container.php line 322 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0):
You have requested a non-existent service \"app.oneup_uploader_namer\". at /vagrant/application/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/
Container.php:322)"}
```

**what should be wrong ?**

**Comment by bytehead** [comment]
Can you please format your config with some [markup](https://help.github.com/articles/creating-and-highlighting-code-blocks/)?

**Comment by milan74sa** [comment]
I did it, do you know how to fix it ?

**Comment by bytehead** [comment]
what does `app/console debug:container | grep namer` (or `bin/console`) display?

**Comment by milan74sa** [comment]
> php bin/console debug:container | grep namer
  oneup_uploader.namer.uniqid Oneup\UploaderBundle\Uploader\Naming\UniqidNamer

**Comment by bytehead** [comment]
your service `app.oneup_uploader_namer` seems not to be registered correctly.

**Comment by milan74sa** [comment]
**ok, I found the problem, it's with**

```yml
services:
    _defaults:
        public: false
```
**it has to be:**
```yml
    app.oneup_uploader_namer:
        class: AppBundle\EventListener\OneupUploaderNamer
        public: true
        arguments: ["@request_stack"]
```
