### ISSUE TITLE
Override Uploader Route. 

### ISSUE THREAD

**Issue by tlorens** [1up-lab/OneupUploaderBundle#282]
I'm not too familiar with Symfony's routing and all the inner-workings.  But is there a way to create a route in `routing.yml` instead of using the auto-magical one provided in the documentation.  Reason being is I have an API route I'd like to use.  

```
api_chunk_upload:
    path: /api/files/chunk/
    defaults: { _controller: FileBundle:UploadChunk:upload }
    methods:  [POST, PUT, PATCH]

```
I can't seem to get this to work. 

Digging through the code, I found in RouteLoader.php where it configures the route. I was able to use this in my routing.yml file.  Seems to be working.  Not sure if this is a 'clean' an acceptable solution.  Anyone?  
```
api_chunk_upload:
    path: /api/files/chunk/
    defaults: { _controller: oneup_uploader.controller.BigUploader:upload }
    methods:  [POST, PUT, PATCH]
```
