### ISSUE TITLE
Missing docs for allowed_mimetypes

### ISSUE THREAD

**Issue by bytehead** [1up-lab/OneupUploaderBundle#318]
Missing docs for `allowed_mimetypes`, see #289.

```
oneup_uploader:
    mappings:
        gallery:
            max_size: 9999990
            allowed_mimetypes:
                image/jpeg: ['jpg', 'jpeg', 'jpe']
```
