### ISSUE TITLE
Little bug in doc

### ISSUE THREAD

**Issue by nicolaspetitjean** [1up-lab/OneupUploaderBundle#320]
Hey !
Just found a small error : [Support a custom Uploader](https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/custom_uploader.md)
I think that it could be wise to note that `name` key have to match mapping key. In other words :
```yml
oneup_uploader:
    mappings:
        gallery:
            frontend: custom
            custom_frontend:
                class: Acme\DemoBundle\Controller\CustomController
                # Change here :
                name: gallery
```
If the name doesn't match, Symfony (4) can't find the service. Maybe if we disable autowiring, that can work, not tested.
