### ISSUE TITLE
Error with custom front end and autowire

### ISSUE THREAD

**Issue by nicolaspetitjean** [1up-lab/OneupUploaderBundle#322]
Hey!
I just wanted to extend existing Dropzone Controller:
```php
<?php
namespace App\Controller\Admin;

use Oneup\UploaderBundle\Controller\DropzoneController;

class CustomController extends DropzoneController
{}
```
And in the config of the bundle:
```yml
oneup_uploader:
    mappings:
        gallery:
            frontend: custom
            custom_frontend:
                class: App\Controller\Admin\CustomController
                name: gallery
```

But it doesn't work because of autowiring.

> Cannot autowire service "App\Controller\Admin\CustomController": argument "$storage" of method "Oneup\UploaderBundle\Controller\AbstractController::__construct()" references interface "Oneup\UploaderBundle\Uploader\Storage\StorageInterface" but no such service exists. You should maybe alias this interface to the existing "oneup_uploader.storage.gallery" service. Did you create a class that implements this interface?

That make sense because symfony doesnot know which services to use. So the first idea was to disable autowiring for my custom controller:
```yml
services:
    App\Controller\Admin\CustomController:
        autowire: false
```
And guess what ? It works. The second idea is to manually add arguments in that file if you don't want to disable  autowiring. A bit annoying. So i wrote a small compiler pass for the bundle. PR comes soon.
