### ISSUE TITLE
Configuration symfony 3.4

### ISSUE THREAD

**Issue by itokia** [1up-lab/OneupUploaderBundle#339]
Hello, I would like to switch my project in v4 symfony and I encounter problems with the configuration.

With the one indicated in the documentation I get the following errors.
`Invalid type for path "oneup_uploader.mappings.id.allowed_mimetypes.0". Expected array, but got string`

My configuration:

```yml
oneup_uploader:
    chunks:
        maxage:               604800
        storage:
            type:               filesystem
            directory:          ~
            filesystem:         ~
            sync_buffer_size:   100K
            stream_wrapper:     ~
            prefix:             'chunks'
        load_distribution:    true
    orphanage:
        maxage:               604800
        directory:            ~
    twig:                 true
    mappings:             # Required

        # Prototype
        id:
            frontend:             blueimp
            custom_frontend:
                name:                 ~
                class:                ~
            storage:
                service:              ~
                type:                 filesystem
                filesystem:           ~
                directory:            ~
                stream_wrapper:       ~
                sync_buffer_size:     100K
            route_prefix:
            endpoints:
                upload: ~
                progress: ~
                cancel: ~
            allowed_mimetypes:     ['image/jpeg','image/png','text/plain','application/pdf','application/vnd.oasis.opendocument.text','application/vnd.oasis.opendocument.spreadsheet','application/vnd.oasis.opendocument.presentation','application/vnd.ms-powerpoint','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document']
                #image/jpeg: ['jpg', 'jpeg', 'jpe']
            disallowed_mimetypes:  []
            error_handler:        oneup_uploader.error_handler.blueimp
            root_folder:          false

            # Set max_size to -1 for gracefully downgrade this number to the systems max upload size.
            max_size:             9223372036854775807
            use_orphanage:        false
            enable_progress:      false
            enable_cancelation:   false
            namer:                oneup_uploader.namer.uniqid
```
