### ISSUE TITLE
OnUpload does not get triggered

### ISSUE THREAD

**Issue by nielzzz1993** [1up-lab/OneupUploaderBundle#352]
I have followed the steps in the github docs, the image gets saved. but the onUpload does not get triggered. I am using this in a symfony 4 application.

config/packages/oneup_uploader.yaml
```
oneup_uploader:
    mappings:
        gallery:
            frontend: dropzone 
            storage:
                directory: "%kernel.root_dir%/../data/uploads/"
```

config/services.yaml
```
App\EventListener\:
    resource: '../src/EventListener/UploadListener.php'
    arguments: ['@doctrine.orm.entity_manager']
    tags: 
        - { name: 'kernel.event_listener', event: 'oneup_uploader.post_persist', method: 'onUpload'}
```

src/EventListener/UploadListener.php
```
<?php

namespace App\EventListener;

use Doctrine\Common\Persistence\ObjectManager;
use Oneup\UploaderBundle\Event\PostPersistEvent;

class UploadListener
{
    /**
     * @var ObjectManager
     */
    private $om;

    public function __construct(ObjectManager $om)
    {
        $this->om = $om;
    }

    public function onUpload(PostPersistEvent $event)
    {
        echo '<script>console.log("SUCCESS")</script>';

        $response = $event->getResponse();
        $response['success'] = true;
        return $response;
    }
}
```

and this is what i have in the twig file
```
<form action="{{ oneup_uploader_endpoint('gallery') }}" class="dropzone" method="post" style="width:200px; height:200px; border:4px dashed black">
                      </form>
```

**Comment by nielzzz1993** [comment]
when i use the command 
`php bin/console debug:event-dispatcher oneup_uploader.post_persist`
it give me the warning
`[WARNING] The event "oneup_uploader.post_persist" does not have any registered listeners.`
So that tells me there is something wrong in services.yaml
But i am not sure what is wrong

**Comment by 47gn** [comment]
Hello :) I have the same problem: Symfony 4.2.3 and I get in the console debug also indicated that no listener is registered.

```
    app.upload_listener:
        class: App\EventListener\UploadListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener. event: oneup_uploader.post_persist, method: onUploadPostPersist}
            - { name: kernel.event_listener. event: oneup_uploader.post_upload, method: onUploadPostUpload}
            - { name: kernel.event_listener. event: oneup_uploader.pre_upload, method: onUploadPreUpload}
```

That the configuration in service.yml - someone an idea what to look for?

Danke :)
