### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by mayconsouza** [1up-lab/OneupUploaderBundle#383]
I'm getting

**Unrecognized options "resource, type" under "oneup_uploader". Available options are "chunks", "mappings", "orphanage", "twig".**

My config structure looks like

```
#app/config/packages/routing.yaml
framework:
    router:
        strict_requirements: ~
        utf8: true

oneup_uploader:
    resource: .
    type: uploader
```

```
#app/config/services.yaml | I inserted in the end of the file
oneup_uploader:
    mappings:
        gallery:
            frontend: dropzone
```

I'm using Symfony 4.4.*
When I add the following code I get the error message:

```
<form action="{{ oneup_uploader_endpoint('gallery') }}" class="dropzone" style="width:200px; height:200px; border:4px dashed black">
</form>
```

**Comment by bytehead** [comment]
The part from your `app/config/packages/routing.yaml` 
```yaml
oneup_uploader:
    resource: .
    type: uploader
```

should probably go to `app/config/routes.yaml`
