### ISSUE TITLE
onUpload UploadListener notwork!!

### ISSUE THREAD

**Issue by nephilimdie** [1up-lab/OneupUploaderBundle#40]
hi, i've problem when i try to use listener. Maybe is my fault. I'm in symfony 2.3 with postgresSQL. I try to use that with sonata media.

``` php

        $request = $event->getRequest();
        $file = $this->getFiles($request->files);
        die(var_dump($file));
        $gallery = $request->get('gallery');
        $file = $request->files->get('upload');
...etc
```

my service

``` yml

services:
  ## post pre update event after persist object
  media.upload_listener:
      class: 'Kdig\MediaBundle\EventListener\UploadListener'
      arguments: [ '@service_container' ]
      tags:
          - { name: container.event_listener, event: oneup_uploader.post_persist, method: onUpload }


```

 "die()" not work.
Can you explain me why?

thanks in advance
regards
Stefano
