### ISSUE TITLE
Error whila upoloading with Symfony 5.2

### ISSUE THREAD

**Issue by Rikijs** [1up-lab/OneupUploaderBundle#404]
### Question

|  boundle | version
|------------ | ------
| symfony | 5.2.6
| oneup/flysystem-bundle | 4.0.6
| oneup/uploader-bundle | 3.1.2

Made an upgrade to `Oneup Flysystem` and `Oneup Uploader` in order to use latest `Flysystem v2`!
Yet i am getting an error while uploading files.

`Argument 1 passed to Oneup\UploaderBundle\Uploader\Storage\FlysystemStorage::__construct() must be an instance of League\Flysystem\FilesystemInterface, instance of League\Flysystem\Filesystem given, called in D:\DEV\Izstrade_WEB_DEV\_DEV_SF5_\zenfiles5\var\cache\dev\Container9LbNvYG\getOneupUploader_Controller_GalleryService.php on line 28`

> relevant part of services.yaml

```
    oneup_flysystem.gallery_filesystem:
        alias: League\Flysystem\Filesystem
        public: true

    League\Flysystem\Local\LocalFilesystemAdapter: '@oneup_flysystem.adapter.local'
    League\Flysystem\MountManager: '@oneup_flysystem.mount_manager'
```

> my oneup_uploader.yaml

```
oneup_uploader:
    mappings:
        gallery:
            storage:
                type: flysystem
                filesystem: oneup_flysystem.gallery_filesystem

            frontend: blueimp
            enable_progress: true
            namer: app.upload_unique_namer

            max_size: !php/const App\Entity\AppConstants::UPLOADABLE_FILE_SIZE_MAX
```

> my oneup_flysystem.yaml

```
oneup_flysystem:
    adapters:
        my_adapter:
            local:
                location: '%data_dir_stored%'

    filesystems:
        default_filesystem:
            adapter: my_adapter
            alias: League\Flysystem\Filesystem
```

I tried changing `League\Flysystem\Filesystem` referrences in YAML to `League\Flysystem\FilesystemInterface`.
It has no effect - the same error persists.

It might be misconfiguration issue or a bug.

Any help would be appreciated, thank you!
