### ISSUE TITLE
S6 : How to call OrphanageManager  

### ISSUE THREAD

**Issue by PauchardThomas** [1up-lab/OneupUploaderBundle#428]
### Question

Hello, following the [controller part from orphanage doc](https://github.com/1up-lab/OneupUploaderBundle/blob/master/doc/orphanage.md#the-controller-part), i'm trying to acces to the OrphanageManager : 

`  $manager = $this->get('oneup_uploader.orphanage_manager')->get('gallery');`

However, `$this->get('')` not existing on AbstractController on Symfony6, and I cannot use DependencyInjection with `Oneup\UploaderBundle\Uploader\Orphanage\OrphanageManager`

How can I call the manager with S6 ?

Thnaks

|    Q        |   A
|------------ | ------
| Version     | 4.0

**Comment by bytehead** [comment]
> and I cannot use DependencyInjection

Why not? Missing autoconfiguration/autowiring?

**Comment by PauchardThomas** [comment]
When I'm trying to inject `Oneup\UploaderBundle\Uploader\Orphanage\OrphanageManager` , here what's i'm getting :
`Cannot autowire argument $manager of "App\Controller\MyController::myfunction()": it references class "Oneup\UploaderBundle\Uploader\Orphanage\OrphanageManager" but no such service exists. You should maybe alias this class to the existing "oneup_uploader.orphanage_manager" service.`

Here my conf : 

```yaml
# Read the documentation: https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/index.md
oneup_uploader:
    mappings:
        # This is a mapping example, remove it and create your own mappings.
        depot:
            #use_orphanage: true
            frontend: dropzone # or any uploader you use in the frontend
            storage:
                directory: "%kernel.project_dir%/public/uploads/depots/"
            use_orphanage: true
    chunks:
        maxage: 86400 # 24h
        storage:
            directory: "%kernel.cache_dir%/uploader/chunks"
    orphanage:
        maxage: 86400 # 24h
        directory: "%kernel.cache_dir%/uploader/orphanage"


```

Should I add something to my services.yaml ?
