### ISSUE TITLE
allowed_mimetypes, the file "" does not exist

### ISSUE THREAD

**Issue by philgagnon12** [1up-lab/OneupUploaderBundle#73]
I set the `allowed_mimetypes` for my mapping, upload a file, the response I get is a 500 Internal Server Error , message  : the file "" does not exist . I guess the uploaded file never makes it to the upload folder and the mimeguesser throws that exception.

```
oneup_uploader:
    mappings:
        xls:
            frontend: blueimp # or any uploader you use in the frontend
            error_handler: oneup_uploader.error_handler.blueimp
            allowed_mimetypes:
                - 'application/vnd.ms-excel'
                - 'application/msexcel'
                - 'application/x-msexcel'
                - 'application/x-ms-excel'
                - 'application/x-excel'
                - 'application/x-dos_ms_excel'
                - 'application/xls'
                - 'application/x-xls'
```
