### ISSUE TITLE
_uploader/gallery/upload 500 (Internal Server Error) jquery.js

### ISSUE THREAD

**Issue by TheRoby** [1up-lab/OneupUploaderBundle#74]
Hi,

Thank's for the bundle !

I tried to use with blueimp. 

config.yml

```
oneup_uploader:
    mappings:
        gallery:
            frontend: blueimp
```

services.yml

```
fa_user.upload_listener:
    class: Fa\UserBundle\EventListener\UploadListener
    arguments: [@doctrine]
    tags:
        - { name: kernel.event_listener, event: oneup_uploader.post_upload, method: onUpload }
```

UploadListener.php

```
<?php
namespace Fa\UserBundle\EventListener;

use Oneup\UploaderBundle\Event\PostPersistEvent;

class UploadListener
{
    public function __construct($doctrine)
    {
        $this->doctrine = $doctrine;
    }

    public function onUpload(PostPersistEvent $event)
    {

    }
}
```

edit.html.twig

```
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script type="text/javascript" src="{{ asset('js/jquery.ui.widget.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/jquery.iframe-transport.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/jquery.fileupload.js') }}"></script>
<script type="text/javascript">
$(document).ready(function()
{
    $('#fileupload').fileupload({});
});
</script>

<input id="fileupload" type="file" name="files[]" data-url="{{ oneup_uploader_endpoint('gallery') }}" multiple />
```

And when i choose a file, i have a "500 (Internal Server Error) jquery.js:8706"
I don't understand why ...
Please help :)

Thanks
