### ISSUE TITLE
How to upload images manually?

### ISSUE THREAD

**Issue by azamalvi** [1up-lab/OneupUploaderBundle#98]
HI!
I am new in Symfony2. I m using sonata media bundle for uploading image.It's working fine but unfortunately it not support multiple image upload. So I use OneupUploaderBundle that uses "Uploadify". 
When I select images and then after selecting it automatically upload the files to folder.Now I want to upload it manually not by selecting and then automatically upload it (actually my goal is to upload it using sonata media bundle.)
this is my EventListener 

``` php
// UploadListener.php
<?php
namespace my\VideoBundle\EventListener;
use Oneup\UploaderBundle\Event\PostPersistEvent;

  class UploadListener
  {
      public function __construct($doctrine)
      {
          $this->doctrine = $doctrine;
      }
      public function onUpload(PostPersistEvent $event)
      {

      }
  }
```

and I register this into config.yml like this

``` yaml
# config.yml
services:
    my_video.listener.upload_listener:
        class: my\VideoBundle\EventListener\UploadListener
        arguments: [@doctrine]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_upload, method: onUpload }
```

Now how can I get all the selected files to be upload manually.Actually I can't find a simple tutorial to do this so I post it here.
Thanks.
